% Compile SeDuMi MEX files.
% compile.m runs with cwd set to the package source root.

fprintf('=== Compiling SeDuMi MEX files ===\n');

srcRoot = pwd;

% Mirror the Matlab branch of upstream install_sedumi.m: 33 MEX targets,
% each grouped with its auxiliary .c dependencies. All bind against
% MATLAB's BLAS (-lmwblas).
targets = { ...
  'bwblkslv.c sdmauxFill.c sdmauxRdot.c', ...
  'choltmpsiz.c', ...
  'cholsplit.c', ...
  ['dpr1fact.c auxfwdpr1.c sdmauxCone.c sdmauxCmp.c sdmauxFill.c ', ...
   'sdmauxScalarmul.c sdmauxRdot.c blkaux.c'], ...
  'symfctmex.c symfct.c', ...
  'ordmmdmex.c ordmmd.c', ...
  'quadadd.c', ...
  'sqrtinv.c sdmauxCone.c', ...
  'givensrot.c auxgivens.c sdmauxCone.c', ...
  'urotorder.c auxgivens.c sdmauxCone.c sdmauxTriu.c sdmauxRdot.c', ...
  ['psdframeit.c reflect.c sdmauxCone.c sdmauxRdot.c sdmauxTriu.c ', ...
   'sdmauxScalarmul.c'], ...
  ['psdinvjmul.c reflect.c sdmauxCone.c sdmauxRdot.c sdmauxTriu.c ', ...
   'sdmauxScalarmul.c blkaux.c'], ...
  'bwdpr1.c sdmauxCone.c sdmauxRdot.c', ...
  'fwdpr1.c auxfwdpr1.c sdmauxCone.c sdmauxScalarmul.c', ...
  'fwblkslv.c sdmauxScalarmul.c', ...
  'qblkmul.c sdmauxScalarmul.c', ...
  'blkchol.c blkchol2.c sdmauxFill.c sdmauxScalarmul.c', ...
  'vecsym.c sdmauxCone.c', ...
  'qrK.c sdmauxCone.c sdmauxRdot.c sdmauxScalarmul.c', ...
  'finsymbden.c sdmauxCmp.c', ...
  'symbfwblk.c', ...
  'ddot.c sdmauxCone.c sdmauxRdot.c sdmauxScalarmul.c', ...
  'partitA.c sdmauxCmp.c', ...
  'getada1.c sdmauxFill.c', ...
  'getada2.c sdmauxCone.c sdmauxRdot.c sdmauxFill.c', ...
  ['getada3.c spscale.c sdmauxCone.c sdmauxRdot.c sdmauxScalarmul.c ', ...
   'sdmauxCmp.c'], ...
  'adendotd.c sdmauxCone.c', ...
  'adenscale.c', ...
  'extractA.c', ...
  'sortnnz.c sdmauxCmp.c', ...
  'iswnbr.c', ...
  'incorder.c', ...
  'findblks.c sdmauxCone.c sdmauxCmp.c', ...
  ['invcholfac.c triuaux.c sdmauxCone.c sdmauxRdot.c sdmauxTriu.c ', ...
   'sdmauxScalarmul.c blkaux.c'], ...
  };

flags = {'-O', '-largeArrayDims'};
if isunix && ~ismac
    % Statically link libstdc++/libgcc so the MEX files load on end-user
    % machines without pulling in the builder's runtime.
    flags{end+1} = 'LDFLAGS=$LDFLAGS -static-libstdc++ -static-libgcc';
end
libs = {'-lmwblas'};

olddir = cd(srcRoot);
cleanup = onCleanup(@() cd(olddir));

for i = 1:length(targets)
    files = strsplit(strtrim(targets{i}));
    [~, first] = fileparts(files{1});
    fprintf('  [%2d/%2d] %s\n', i, length(targets), first);
    mex(flags{:}, files{:}, libs{:});
end

fprintf('=== SeDuMi MEX compilation complete ===\n');
